$SubscriptionId = "70c2f543-67b0-47d9-ab82-72a1e06fa0bc"
$ResourceGroup = "Assignment4"
$LogAnalyticsWorkspaceName = "Assignment4Workspace"
$LogAnalyticsTableName = "Log_CL"
$DataCollectionRuleName = "Assignment4DCR"
$DataCollectionEndpointName = "Assignment4DCE"
$FunctionAppName = "Assignment4Func"
$ApiManagementGatewayName = ""