name: Azure Login with OIDC
on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: jc-oidc-app    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.9'           # set this to the dot net version to use

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Run dotnet build and publish
      - name: 'Show Connection Success'
        run: |
          az account show
          
      # Deploy to Azure Web app
    
      - name: logout
        run: |
          az logout
