name: Run Azure Login with OpenID Connect
on: [push,workflow_dispatch]

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production 
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - run: |
          echo ${{ vars.AZURE_CLIENT_ID }}
          echo ${{ vars.AZURE_TENANT_ID }}
          echo ${{ vars.AZURE_SUBSCRIPTION_ID }}          
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
    - name: 'Run Azure CLI commands'
      run: az account show          
