name: Assignment 1

on:
  push:
    branches:
      - Assignment1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID_CREATED_SP }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: List Azure Resources
      run: |
        az account show
        az resource list --output table

      env:
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
