name: Azure Login with OIDC
on:
  push:
    branches:
      - Assignment1
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show Connection Success
        run: az account show

      - name: List Azure resources
        run: az resource list

      - name: Logout
        run: az logout
