name: Azure Login with OIDC
on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: jc-oidc-app    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.9'           # set this to the dot net version to use

jobs:
  deploy:
    runs-on: windows-latest
    environment: Deployment
    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Show Connection Success
      - name: 'Show Connection Success'
        run: |
          az account show

      # List Resources
      - name: 'List Resources'
        run: |
          az resource list

      # Deploy to Azure Web app
    
      - name: logout
        run: |
          az logout
