name: Assignment 1

on:
  push:
    branches:
      - Assignment1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # You need to set up Azure credentials as a secret in your repository.

    - name: List Azure Resources
      run: |
        az account show
        az resource list --output table


        # Then run your PowerShell script with 'pwsh -File Assignment1.ps1'.

      env:
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
