name: Azure Login with OIDC
on:
  push:
    branches:
      - Assignment1
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show Connection Success
        run: az account show

      # Extra credit
      - name: Create resource group
        run: |
          az staticwebapp create -g EWU-CSCD396-2023-Fall -n tempStaticWebsite

      - name: List Azure resources
        run: |
          az resource list

      - name: Remove resource group
        run: |
          az staticwebapp delete -n tempStaticWebsite -y

      - name: Logout
        run: |
          az logout

