name: Assignment 1

on:
  push:
    branches:
      - Assignment1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run PowerShell script
      run: |
        # Authenticate to Azure using the App ID and perform necessary actions.
        # For example, you can use 'az login' with the App ID credentials.

        name: Your Workflow Name
on:
  workflow_dispatch:
jobs:
  your-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Install Azure CLI
        run: |
          # Check if the Azure CLI is already installed
          if ! az --version; then
            # If not installed, install the Azure CLI
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi

      # Your other workflow steps go here
      - name: Another Step
        run: echo "This is another step in your workflow."

      # Add more steps as needed

        # Then run your PowerShell script with 'pwsh -File Assignment1.ps1'.

      env:
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
