on: [push]

name: AzurePowerShellLoginSample

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.ASSIGNMENT1_CREDENTIALS}}
        enable-AzPSSession: true 
     
    - name: Deploy ARM Template
      uses: azure/CLI@v1
      with:
        inlineScript: |
          Get-AzResource
